### ISSUE TITLE
怎样编译23.05.4版本，修改了.github/workflows三个*.yml的一些地方报错，应该怎样修改

### ISSUE THREAD

**Issue by adwzlad** [217heidai/OpenWrt-Builder#2]
update-checker.yml
env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-23.05.4

build-router.yml
env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-23.05.4
  VERSION: 23.05.4
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2-router.sh
  TZ: Asia/Shanghai

build-gateway.yml
env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-23.05.4
  VERSION: 23.05.4
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2-gateway.sh
  TZ: Asia/Shanghai

**Comment by adwzlad** [comment]
不改版本号正常编译

**Comment by 217heidai** [comment]
23.05.4 版本对应 openwrt-23.05 分支的 release tag v23.05.4，只需要修改 REPO_BRANCH 就行了：
```bash
REPO_BRANCH: v23.05.4
```
其实直接用 openwrt-23.05 分支编译就是最新的 23.05.x 版本。
